# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: script_server.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13script_server.proto\"\x1c\n\rScriptRequest\x12\x0b\n\x03req\x18\x01 \x01(\t\"\x1d\n\x0eScriptResponse\x12\x0b\n\x03rsp\x18\x01 \x01(\t2<\n\x0cScriptServer\x12,\n\tRunScript\x12\x0e.ScriptRequest\x1a\x0f.ScriptResponseB:Z8github.com/tigranftp/grpc_random_py_script/script_serverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'script_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/tigranftp/grpc_random_py_script/script_server'
  _globals['_SCRIPTREQUEST']._serialized_start=23
  _globals['_SCRIPTREQUEST']._serialized_end=51
  _globals['_SCRIPTRESPONSE']._serialized_start=53
  _globals['_SCRIPTRESPONSE']._serialized_end=82
  _globals['_SCRIPTSERVER']._serialized_start=84
  _globals['_SCRIPTSERVER']._serialized_end=144
# @@protoc_insertion_point(module_scope)
