// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: script_server.proto

package script_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScriptServerClient is the client API for ScriptServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScriptServerClient interface {
	RunScript(ctx context.Context, in *ScriptRequest, opts ...grpc.CallOption) (*ScriptResponse, error)
}

type scriptServerClient struct {
	cc grpc.ClientConnInterface
}

func NewScriptServerClient(cc grpc.ClientConnInterface) ScriptServerClient {
	return &scriptServerClient{cc}
}

func (c *scriptServerClient) RunScript(ctx context.Context, in *ScriptRequest, opts ...grpc.CallOption) (*ScriptResponse, error) {
	out := new(ScriptResponse)
	err := c.cc.Invoke(ctx, "/ScriptServer/RunScript", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScriptServerServer is the server API for ScriptServer service.
// All implementations must embed UnimplementedScriptServerServer
// for forward compatibility
type ScriptServerServer interface {
	RunScript(context.Context, *ScriptRequest) (*ScriptResponse, error)
	mustEmbedUnimplementedScriptServerServer()
}

// UnimplementedScriptServerServer must be embedded to have forward compatible implementations.
type UnimplementedScriptServerServer struct {
}

func (UnimplementedScriptServerServer) RunScript(context.Context, *ScriptRequest) (*ScriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunScript not implemented")
}
func (UnimplementedScriptServerServer) mustEmbedUnimplementedScriptServerServer() {}

// UnsafeScriptServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScriptServerServer will
// result in compilation errors.
type UnsafeScriptServerServer interface {
	mustEmbedUnimplementedScriptServerServer()
}

func RegisterScriptServerServer(s grpc.ServiceRegistrar, srv ScriptServerServer) {
	s.RegisterService(&ScriptServer_ServiceDesc, srv)
}

func _ScriptServer_RunScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptServerServer).RunScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ScriptServer/RunScript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptServerServer).RunScript(ctx, req.(*ScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScriptServer_ServiceDesc is the grpc.ServiceDesc for ScriptServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScriptServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ScriptServer",
	HandlerType: (*ScriptServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunScript",
			Handler:    _ScriptServer_RunScript_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "script_server.proto",
}
